Add new digital garden note
hashpire/eureka-web3 pull request #14
Opened 2022-02-07 08:37 UTC by Punptts

Please review my artwork

2022-02-07 18:01 UTC, anakornk requested changes

2022-02-08 02:58 UTC, Punptts commented on 00 - Notes/Digital Garden คืออะไร?.md
> +ในโลกของข้อมูลประกอบไปด้วย Data, Information, Knowledge และ Insight ข้อมูลต่าง ๆ ไหลผ่านตัวเรา จากข้อมูลปกติทั่วไปได้ถูกกลั่นกรองตามลำดับจนกลายมาเป็น Insight หรือความรู้ความเข้าใจที่สามารถนำไปต่อยอดไ
งั้นประเด็นนี้ปันขอไปเขียนแยกเป็น post เกี่ยวกับ information overload ได้ไหมะ โพสต์อันนี้เน้นอธิบาย garden ไปเลยแบบนี้ได้ไหมคะ

2022-02-08 03:03 UTC, Boomgeek commented
ขอเสริม ถ้าเพิ่มการเปรียบเทียบ ระหว่าง Blog ปกติ กับ Digital garden เข้าไปด้วยน่าจะเสริมความเข้าใจได้มากขึ้น ทำเป็นตาราง Compares ก็น่าจะดีนะครับ

2022-02-08 04:23 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +ในโลกของข้อมูลประกอบไปด้วย Data, Information, Knowledge และ Insight ข้อมูลต่าง ๆ ไหลผ่านตัวเรา จากข้อมูลปกติทั่วไปได้ถูกกลั่นกรองตามลำดับจนกลายมาเป็น Insight หรือความรู้ความเข้าใจที่สามารถนำไปต่อยอดไ
ได้เลย

2022-02-08 04:23 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +ในโลกของข้อมูลประกอบไปด้วย Data, Information, Knowledge และ Insight ข้อมูลต่าง ๆ ไหลผ่านตัวเรา จากข้อมูลปกติทั่วไปได้ถูกกลั่นกรองตามลำดับจนกลายมาเป็น Insight หรือความรู้ความเข้าใจที่สามารถนำไปต่อยอดไ
หรือจะอันเดียวกัน แต่เป็นหลายๆรุป แนว carousel ก็ได้

2022-02-08 06:44 UTC, anakornk requested changes

2022-02-08 06:44 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +Digital Garden หรือ สวนดิจิทัล คือฐานความรู้ในรูปแบบของโน๊ตที่สร้างความสัมพันธ์ระหว่างกันโดยเน้นการเชื่อมโยงกันที่เนื้อหา ไม่เน้นวันที่และเวลาในการเผยแพร่ สวนดิจิทัลมีลักษะเป็นกราฟ หรือ Knowledge Gra
"สวนดิจิทัลมีลักษะเป็นกราฟ หรือ Knowledge Graph"
Digital Gardenก็คือ Knowledge Graphแบบนึง เป็น กราฟที่ link knowledge ไม่ใช่ลักษณะเหมือน

2022-02-08 07:02 UTC, anakornk requested changes

2022-02-08 07:02 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +สวนดิจิทัลเป็นเหมือนตัวช่วยในการสร้างระบบการจัดการความรู้ โดยที่เราสามารถสร้างโน๊ตจากข้อมูลต่าง ๆ ที่พบเจอในแต่ละวัน หัวใจสำคัญของการเขียนโน๊ตแบบสวนดิจิทัลคือ ความคิดที่ไม่สมบูรณ์ เราสามารถเริ่มคิดแล
"เมื่อมีโอกาสก็สามารถประกอบโน๊ตแต่ละอันเข้าด้วยกันจน" 
หาคำอื่นแทนประกอบ ถ้า eng คือ Refactor.
Refactor สามารถเป้นการเชื่อม/link การ merge การextract, etc.

2022-02-08 07:04 UTC, Boomgeek requested changes

2022-02-08 10:33 UTC, Punptts commented
Artwork สำหรับเนื้อหาบทความอันล่าสุดค่ะ

![what-is-digital-garden](https://user-images.githubusercontent.com/69186230/152969794-7193aeab-f5e6-4829-a177-6f7f0a69b4d6.png)

2022-02-08 10:40 UTC, Punptts commented
> Artwork สำหรับเนื้อหาบทความอันล่าสุดค่ะ
> 
> ![what-is-digital-garden](https://user-images.githubusercontent.com/69186230/152969794-7193aeab-f5e6-4829-a177-6f7f0a69b4d6.png)

Blog Posts เขียนผิดเอาตัว s ออกแล้วนะคะเป็น Blog Post
รอ comment  เผื่อมีแก้แล้วจะ push ตัวที่แก้ไขแล้วขึ้นไปอีกทีค่ะ

2022-02-08 10:44 UTC, anakornk commented
> Artwork สำหรับเนื้อหาบทความอันล่าสุดค่ะ
> 
> ![what-is-digital-garden](https://user-images.githubusercontent.com/69186230/152969794-7193aeab-f5e6-4829-a177-6f7f0a69b4d6.png)

https://tomcritchlow.com/2018/10/10/of-gardens-and-wikis/
Stream, Campfires and Gardens

2022-02-08 10:49 UTC, anakornk commented
Note links หมายถึงอะไร ?
ถ้าชี้ไปาหาnote ควรจะเป็น Linked Notes

2022-02-08 10:50 UTC, anakornk commented
Knowledge Graph ถ้า ตัวwordแรก capใหญ่word สองก็ควรจะ cap ใหญ่

2022-02-11 03:49 UTC, anakornk commented
1. Naming Consistency
Streams, Campfires, Gardens
Stream, Campfire, Garden
Digital Stream, Digital Campfire, Digital Garden (ถ้าไม่ยาวอันนี้น่าจะดีสุด)

2. Capitalization Consistency
Social media -> Socia Media
หลัง colon ไม่ควร cap เพราะอยู่ใน phraseเดียวกัน
จะเอา fast content ออกก็ได้ อันนี้มันสื่อได้ถึงอย่างอื่น

2022-02-11 03:55 UTC, anakornk commented
Description ต้องเปลี่ยน 
Blog แค่ exampleของ Campfire ไม่ใช่ แค่ blog posts fade away over time
ไม่ควรมีคำว่า blog post
e.g. Slow burns, Fade away over time.
Blog เป็นแค่ example

Social media example ของ Stream

Description ของ garden ควรจะเป็น evergreen, link อะไรมากกว่า emphasis ผิดที่

2022-02-11 04:36 UTC, Punptts commented
artwork แก้ไขตามคอมเมนต์แล้วค่ะ

![stream-campfure-garden](https://user-images.githubusercontent.com/69186230/153538142-96f4c0db-7876-4a1d-8c77-307f25bde0e8.png)

2022-02-11 04:40 UTC, anakornk commented
ลองหา descriptionของ gardenที่ดีกว่านี้
ตรงรูปอาจจะไม่ต้องชี้ไปหาnotes ไปหาลิ้งก็ได้ เพราะอย่าง blog มันไม่ใช่ notes 
และเขียนเป็น linksแทน

2022-02-11 06:23 UTC, Punptts commented
แก้ไข artwork ตาม comment ล่าสุดค่ะ

![stream-campfire-garden](https://user-images.githubusercontent.com/69186230/153546102-eb54c31f-8258-4539-9ba6-cbefbc1e3131.png)

2022-02-11 08:46 UTC, anakornk commented
> แก้ไข artwork ตาม comment ล่าสุดค่ะ
> 
> ![stream-campfire-garden](https://user-images.githubusercontent.com/69186230/153546102-eb54c31f-8258-4539-9ba6-cbefbc1e3131.png)

Good!

2022-02-14 02:24 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +การเขียนเพื่อแบ่งปันข้อมูลในพื้นที่สาธารณะมักถูกสร้างขึ้นในรูปแบบของ โพสต์ หรือ บล็อก ที่เน้นการอธิบายข้อมูลเป็นบทความยาว ๆ และใช้เวลาในการสร้างค่อนข้างนาน แต่ในขณะเดียวกัน เนื้อหาเหล่านี้ก็มักจะเก่า
ที่เพิ่มมาโอเค ที่ติดคือโพสถือว่ายาว？

2022-02-14 02:24 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +การเขียนเพื่อแบ่งปันข้อมูลในพื้นที่สาธารณะมักถูกสร้างขึ้นในรูปแบบของ โพสต์ หรือ บล็อก ที่เน้นการอธิบายข้อมูลเป็นบทความยาว ๆ และใช้เวลาในการสร้างค่อนข้างนาน แต่ในขณะเดียวกัน เนื้อหาเหล่านี้ก็มักจะเก่า
social post กับ blog มันไม่น่าจะเหมือนกันนะ

2022-02-14 02:27 UTC, anakornk requested changes
para 1 กับ 2 ไม่ค่อยเข้ากัน

2022-02-14 02:27 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +การเขียนเพื่อแบ่งปันข้อมูลในพื้นที่สาธารณะมักถูกสร้างขึ้นในรูปแบบของ โพสต์ หรือ บล็อก ที่เน้นการอธิบายข้อมูลเป็นบทความยาว ๆ และใช้เวลาในการสร้างค่อนข้างนาน แต่ในขณะเดียวกัน เนื้อหาเหล่านี้ก็มักจะเก่า
เก่าทันที แรงไปไหม

2022-02-14 02:32 UTC, anakornk requested changes

2022-02-14 02:32 UTC, anakornk commented on 00 - Notes/Digital Garden คืออะไร?.md
> +[https://hashpire.io/](https://l.facebook.com/l.php?u=https%3A%2F%2Fhashpire.io%2F%3Ffbclid%3DIwAR2M0PMyO2ejqMKDaYcAQpgqPrlCAGjb_CYc2w9h6WMITr4U5DUeDpJDSRk&h=AT33J-54H53uZuXKvVEcLSm4N1ZtIHw6EwHthRnnG
อันนี้ไม่ต้องมี

2022-02-14 02:58 UTC, Punptts commented on 00 - Notes/Digital Garden คืออะไร?.md
> +[https://hashpire.io/](https://l.facebook.com/l.php?u=https%3A%2F%2Fhashpire.io%2F%3Ffbclid%3DIwAR2M0PMyO2ejqMKDaYcAQpgqPrlCAGjb_CYc2w9h6WMITr4U5DUeDpJDSRk&h=AT33J-54H53uZuXKvVEcLSm4N1ZtIHw6EwHthRnnG
สำหรับอันนี้ edit note (5) ปันยังมี paragraph

"สวนดิจิตอลเป็นเหมือน..... ให้กับเราและผู้คนที่มาชมสวนดิจิทัลของเรา"

อยู่นะคะ ปันตั้งใจว่าจะใชำคำว่า "ระบบการจัดการความรู้" เพื่อลิงก์ไปหา note Knowledge Management ค่ะ ส่วนตัวก็มองว่ามันก็เป็นการขยายความ character ของ digital garden ด้วย 

ถ้าเก็บส่วนนี้ไว้จะดีกว่าไหมคะ

2022-02-14 05:13 UTC, Boomgeek approved these changes

2022-02-14 05:57 UTC, anakornk approved these changes

2022-02-14 06:01 UTC, merged