Parinyar/add internet article #2
hashpire/eureka-web3 pull request #16
Opened 2022-02-07 09:13 UTC by tehtrippy

# Social Post - หัวข้อเกี่ยวกับอินเทอร์เน็ต (2)
- Evolution of Communication, Internet, ISP

![image](https://user-images.githubusercontent.com/62202111/152758684-4d2fb8d0-2012-4110-8d33-818e4e90c141.png)

2022-02-08 04:16 UTC, anakornk commented on 00 - Notes/อินเทอร์เน็ต, ISP.md
> +
test

2022-02-15 02:15 UTC, Boomgeek requested changes

2022-02-15 02:15 UTC, Boomgeek commented on 00 - Notes/อินเทอร์เน็ต, ISP.md
> +
จาก
"และ วิธีการเชื่อมต่อเครือข่ายอินเทอร์เน็ตระหว่างประเทศนั้น"
กับ
"และประเทศปลายทาง"

พี่ว่าต้องเลือกสักอย่าง หากใช้ และ/หรือ เป็นตัวเชื่อมจะต้องทำอย่างไร
1. เอและบี
2. เอ และ บี
3. เอ และบี

ถ้าเลือกได้แล้วควรใช้เป็นมาตรฐานในทุกบทความ หรืออย่างน้อยๆ ในบทความเดียวกันไม่ควรมีหลายรูปแบบครับ

แต่ถ้าหากเป็น ภาษาอังกฤษ พี่คิดว่าจะถูกยกเว้น ทำให้สามารถมีเว้นวรรคอยู่หน้าและหลังได้เพื่อเว้นคำ เช่น
A และ B เป็นต้น

@anakornk  คิดว่าอย่างไร?

2022-02-15 02:15 UTC, Boomgeek commented on 00 - Notes/อินเทอร์เน็ต, ISP.md
> +Internet Service Provider (ISP) คือ บริษัทผู้ให้บริการอินเทอร์เน็ต ทำหน้าที่เป็นตัวกลางในการเชื่อมต่อระบบเครือข่ายของลูกค้าเข้ากับเครือข่ายอินเทอร์เน็ต ทำให้ลูกค้าสามารถเข้าถึงบริการต่างๆ บนอินเทอร์เ
ไหนๆ บทความนี้เพื่อคนไทยอยู่แล้ว ยกตัวอย่างเลยมั้ยครับว่าผู้ให้บริการ internet มีใคร เช่น true ais ... ไรงี้ 

@anakornk  จะติดประเดนเรื่องโฆษณามั้ย? แต่พี่ว่ามันเข้าใจง่ายดีนะถ้ามีตัวอย่างที่ชัดเจน

2022-03-07 06:51 UTC, merged