[Note] - What is Internet ?
hashpire/eureka-web3 pull request #26
Opened 2022-02-07 09:59 UTC by tehtrippy

2022-02-07 11:07 UTC, anakornk requested changes

2022-02-07 11:07 UTC, anakornk commented on 00 - Notes/อินเทอร์เน็ตคืออะไร.md
> +**Internet** คือระบบเครือข่ายคอมพิวเตอร์ขนาดใหญ่ ที่ประกอบไปด้วยเครือข่ายย่อยทั้งจากส่วนบุคคลหรือจากองค์กร ในช่วงปี 1963 หน่วยงาน ARPA (Advanced Research Projects Agency) ซึ่งเป็นหน่วยงานที่อยู่ภายใต
ใช้ภาษาไทย"Protocol TCP/IP" อธิบายเพิ่มเติมเกี่ยวกับ TCP/IP สั้นๆ ไม่กี่คำ หลังจากนั้นให้สร้างลิ้งไปหา TCP/IP

2022-02-07 11:07 UTC, anakornk commented on 00 - Notes/อินเทอร์เน็ตคืออะไร.md
> +**Internet** คือระบบเครือข่ายคอมพิวเตอร์ขนาดใหญ่ ที่ประกอบไปด้วยเครือข่ายย่อยทั้งจากส่วนบุคคลหรือจากองค์กร ในช่วงปี 1963 หน่วยงาน ARPA (Advanced Research Projects Agency) ซึ่งเป็นหน่วยงานที่อยู่ภายใต
Note: ในfilename ถ้ามี '/' เหมือนมันจะสร้างfolder

2022-02-08 08:24 UTC, anakornk requested changes

2022-02-08 08:24 UTC, anakornk commented on 00 - Notes/อินเทอร์เน็ตคืออะไร.md
> +**Internet** คือระบบเครือข่ายคอมพิวเตอร์ขนาดใหญ่ ที่ประกอบไปด้วยเครือข่ายย่อยทั้งจากส่วนบุคคลหรือจากองค์กร ในช่วงปี 1963 หน่วยงาน ARPA (Advanced Research Projects Agency) ซึ่งเป็นหน่วยงานที่อยู่ภายใต
TCP/IP คือ TCP + IP
ถ้า Eng "The Internet protocol suite, commonly known as TCP/IP, is the **set of communications protocols** used in the Internet and similar computer networks."
ไม่ใช่ protocols แต่เป็นรวม protocol

แต่โอเค TCP/IP เยอะสุด


IP ย่อจาก Internet Protocol, IP เดียวกับ IP Address
อะไรที่อยู่บนlayer IP ขึ้นไปถือว่าอยู่บน internet หมด
![1_2B15_AHbTIF8j9VBwmKCtw](https://user-images.githubusercontent.com/8156002/152946441-55d7d16a-cead-4292-9fc3-7d65fcfd96e0.jpg)

2022-02-15 08:29 UTC, tehtrippy commented
- merged **parinyar/add-what-is-tcp-ip-note** & **parinyar/add-what-is-ip-address-note**
- notes what is
  - internet
  - tcp/ip
  - ip address
  - ipv4
  - ipv6

2022-02-17 03:01 UTC, tehtrippy commented
merged **parinyar/add-what-is-tcp-ip-note**

2022-03-07 06:27 UTC, merged