[Note] - What is Web 2.0
hashpire/eureka-web3 pull request #28
Opened 2022-02-07 10:07 UTC by tehtrippy

2022-02-07 18:11 UTC, anakornk requested changes

2022-02-07 18:11 UTC, anakornk commented on 00 - Notes/เว็บ 2.0 คืออะไร.md
> +**Web 2.0** เกิดขึ้นเมื่อต้นปี 2000 และยังเป็นรูปแบบเว็บไซต์ที่มีจำนวนมากที่สุดในปัจจุบัน เป็นเว็บไซต์ที่ผู้ใช้งาน นอกเหนือจากการอ่านข้อมูลภายในเว็บไซต์ได้แล้วยังสามารถสร้าง Content ต่างๆ ได้อีกด้วย
Web 2.0 ไม่ใช่ Website

2022-02-07 18:11 UTC, anakornk commented on 00 - Notes/เว็บ 2.0 คืออะไร.md
> +**Web 2.0** เกิดขึ้นเมื่อต้นปี 2000 และยังเป็นรูปแบบเว็บไซต์ที่มีจำนวนมากที่สุดในปัจจุบัน เป็นเว็บไซต์ที่ผู้ใช้งาน นอกเหนือจากการอ่านข้อมูลภายในเว็บไซต์ได้แล้วยังสามารถสร้าง Content ต่างๆ ได้อีกด้วย
Interactive?

2022-02-07 18:11 UTC, anakornk commented on 00 - Notes/เว็บ 2.0 คืออะไร.md
> +**Web 2.0** เกิดขึ้นเมื่อต้นปี 2000 และยังเป็นรูปแบบเว็บไซต์ที่มีจำนวนมากที่สุดในปัจจุบัน เป็นเว็บไซต์ที่ผู้ใช้งาน นอกเหนือจากการอ่านข้อมูลภายในเว็บไซต์ได้แล้วยังสามารถสร้าง Content ต่างๆ ได้อีกด้วย
"โดยรูปแบบ Model การติดต่อสื่อสารจะหว่าง Client และ Server จะเป็นแบบ Client and Server Model" ทั่วไปอ่านไม่เข้าใจ

2022-02-07 18:11 UTC, anakornk commented on 00 - Notes/เว็บ 2.0 คืออะไร.md
> +**Web 2.0** เกิดขึ้นเมื่อต้นปี 2000 และยังเป็นรูปแบบเว็บไซต์ที่มีจำนวนมากที่สุดในปัจจุบัน เป็นเว็บไซต์ที่ผู้ใช้งาน นอกเหนือจากการอ่านข้อมูลภายในเว็บไซต์ได้แล้วยังสามารถสร้าง Content ต่างๆ ได้อีกด้วย
ผ่านตัวกลาง ?

2022-02-17 03:15 UTC, tehtrippy commented
merged **parinyar/add-problems-of-web-2.0-note**

2022-03-07 06:28 UTC, merged